# Generated by Django 6.1 on 2026-09-02 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=200)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identified'), ('VERIFIED', 'Verified'), ('NOTIFIED', 'Notified'), ('ACQUIRED', 'Acquired'), ('POSSESSION', 'Possession Taken')], default='IDENTIFIED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='land.project')),
            ],
        ),
    ]
