# Generated by Django 6.1 on 2026-09-05 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0003_compensation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RRCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=200)),
                ('displaced', models.BooleanField(default=False)),
                ('rehabilitation_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30)),
                ('assistance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_cases', to='land.project')),
            ],
        ),
    ]
