# Generated by Django 6.1 on 2026-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0005_possession'),
    ]

    operations = [
        migrations.AddField(
            model_name='landparcel',
            name='boundary',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
