# Generated by Django 6.1 on 2026-09-17 19:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0006_landparcel_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='landparcel',
            name='boundary_geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
