# Generated by Django 6.1 on 2026-09-19 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0007_landparcel_boundary_geometry_landparcel_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='site_photos/')),
                ('category', models.CharField(choices=[('BEFORE', 'Before Acquisition'), ('DURING', 'During Acquisition'), ('AFTER', 'After Possession'), ('SITE', 'Site Condition'), ('OTHER', 'Other')], default='SITE', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_photos', to='land.landparcel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_photos', to='land.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
