# Generated by Django 6.1 on 2026-09-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0009_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('UPLOAD', 'Uploaded'), ('PAYMENT', 'Payment'), ('STATUS_CHANGE', 'Status Change')], max_length=20),
        ),
    ]
